name: Smoke

on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install shellcheck (optional)
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck || true

      - name: Run smoke tests
        run: bash scripts/smoke.sh

  ubuntu-modules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prime sudo session
        run: sudo true

      - name: Run Ubuntu module smoke suite
        run: bash scripts/test_ubuntu_modules.sh
